/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eye;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nikhil
 */
public class contrast extends javax.swing.JPanel {

    /**
     * Creates new form contrast
     */
    int levelno=0,cscore=0;
    Font f0=new Font("Tahoma",12,90);
      //Font f0=new Font("Trajan Pro ",4,60);
    Font f1=new Font("Tahoma",12,70);
    Font f2=new Font("Tahoma",12,50);
    Font f3=new Font("Tahoma",12,30);
    Font f4=new Font("Tahoma",12,20);
    Font f5=new Font("Tahoma",12,10);
    Boolean wait;
    public contrast() {
        
        initComponents();
        try {
                BrightnessManager.setBrightness(10);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        charactor = new javax.swing.JLabel();
        questian = new javax.swing.JLabel();
        bfirst = new javax.swing.JButton();
        bsecond = new javax.swing.JButton();
        bthird = new javax.swing.JButton();
        bfourth = new javax.swing.JButton();
        contrastover = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        charactor.setFont(new java.awt.Font("Trajan Pro 3", 0, 48)); // NOI18N
        charactor.setText("K");

        questian.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        questian.setForeground(new java.awt.Color(255, 0, 51));
        questian.setText("what do you see?");

        bfirst.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bfirst.setText("k");
        bfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfirstActionPerformed(evt);
            }
        });

        bsecond.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bsecond.setText("q");
        bsecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsecondActionPerformed(evt);
            }
        });

        bthird.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bthird.setText("u");
        bthird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthirdActionPerformed(evt);
            }
        });

        bfourth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bfourth.setText("p");
        bfourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfourthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questian, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bfourth, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bthird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bsecond, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(charactor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(charactor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(questian)
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfirst)
                    .addComponent(bthird))
                .addGap(35, 35, 35)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfourth)
                    .addComponent(bsecond))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contrastoverLayout = new javax.swing.GroupLayout(contrastover);
        contrastover.setLayout(contrastoverLayout);
        contrastoverLayout.setHorizontalGroup(
            contrastoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contrastoverLayout.setVerticalGroup(
            contrastoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.remove(jPanel2);
        jPanel1.add(panel1);
        levelno++;
        panel1.setSize(jPanel1.getWidth(),jPanel1.getWidth());
        jPanel1.repaint();
        jPanel1.revalidate();
        charactor.setFont(f0);
        
      
        
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfirstActionPerformed
        // TODO add your handling code here:
        if(levelno==1)
        {
             try {
                BrightnessManager.setBrightness(25);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
       charactor.setText("H");
       charactor.setForeground(new java.awt.Color(100,100,100));
           
       
       bfirst.setText("T");
       bsecond.setText("J");
       bthird.setText("H");
       bfourth.setText("K");
       charactor.setFont(f1);
       levelno=2;
       cscore++;
       return;
       
        }
        if(levelno==2)
        {
            try {
                BrightnessManager.setBrightness(50);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
           charactor.setText("L");
       bfirst.setText("M");
       bsecond.setText("J");
       bthird.setText("K");
       bfourth.setText("L");  
       levelno=3;
       charactor.setForeground(new java.awt.Color(150,150,150));
       charactor.setFont(f2);
       return;
       
        }
        if(levelno==3)
        {
             try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("A");
       bfirst.setText("Z");
       bsecond.setText("X");
       bthird.setText("B");
       bfourth.setText("A");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(200,200,200));
          charactor.setFont(f3);
        return;
        
        }
        if(levelno==4)
        {
             try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("Q");
       bfirst.setText("R");
       bsecond.setText("Q");
       bthird.setText("C");
       bfourth.setText("D");  
       levelno=5;  
        charactor.setForeground(new java.awt.Color(220,220,220));
        charactor.setFont(f4);
        return;
        
        }
         if(levelno==5)
          {
                try {
                BrightnessManager.setBrightness(100);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("T");
       bfirst.setText("P");
       bsecond.setText("S");
       bthird.setText("T");
       bfourth.setText("U");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(230,230,230));
        charactor.setFont(f5);
        return;
              
          }
        
    }//GEN-LAST:event_bfirstActionPerformed

    private void bthirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthirdActionPerformed
        // TODO add your handling code here:
         if(levelno==1)
        {
             try {
                BrightnessManager.setBrightness(25);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
       charactor.setText("H");
       bfirst.setText("T");
       bsecond.setText("J");
       bthird.setText("H");
       bfourth.setText("K");
       levelno=2;
       charactor.setFont(f1);
       charactor.setForeground(new java.awt.Color(100,100,100));
        
       return;
        }
         if(levelno==2)
        {
             try {
                BrightnessManager.setBrightness(50);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
           charactor.setText("L");
       bfirst.setText("M");
       bsecond.setText("J");
       bthird.setText("K");
       bfourth.setText("L");  
       cscore++;
       levelno=3;
           charactor.setForeground(new java.awt.Color(150,150,150));
           charactor.setFont(f2);
           return;
          
        }
          if(levelno==3)
        {
            try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
          charactor.setText("A");
       bfirst.setText("Z");
       bsecond.setText("X");
       bthird.setText("B");
       bfourth.setText("A");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(200,200,200));
        charactor.setFont(f3);
        return;
         
        }
          if(levelno==4)
        {
             try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("Q");
       bfirst.setText("R");
       bsecond.setText("Q");
       bthird.setText("C");
       bfourth.setText("D");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(220,220,220));
        charactor.setFont(f4);
        return;
        
        }
          if(levelno==5)
          {
                try {
                BrightnessManager.setBrightness(100);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("T");
       bfirst.setText("P");
       bsecond.setText("S");
       bthird.setText("T");
       bfourth.setText("U");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(230,230,230));
        charactor.setFont(f5);
        return;
              
          }
         
        
    }//GEN-LAST:event_bthirdActionPerformed

    private void bfourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfourthActionPerformed
        // TODO add your handling code here:
         if(levelno==1)
        {
             try {
                BrightnessManager.setBrightness(25);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
       charactor.setText("H");
       
       bfirst.setText("T");
       bsecond.setText("J");
       bthird.setText("H");
       bfourth.setText("K");
       charactor.setFont(f1);
       levelno=2;
       charactor.setForeground(new java.awt.Color(100,100,100));
        
       return;
        }
         if(levelno==2)
        {
            try {
                BrightnessManager.setBrightness(50);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
           charactor.setText("L");
       bfirst.setText("M");
       bsecond.setText("J");
       bthird.setText("K");
       bfourth.setText("L"); 
       levelno=3;
          charactor.setForeground(new java.awt.Color(150,150,150));
          charactor.setFont(f2);
          return;
          
        }
         if(levelno==3)
         {
              try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
           charactor.setText("A");
       bfirst.setText("Z");
       bsecond.setText("X");
       bthird.setText("B");
       bfourth.setText("A");  
       levelno++;
       cscore++;
        charactor.setForeground(new java.awt.Color(200,200,200));
        charactor.setFont(f3);
        return;
        
         }
         if(levelno==4)
        {
            try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("Q");
       bfirst.setText("R");
       bsecond.setText("Q");
       bthird.setText("C");
       bfourth.setText("D");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(220,220,220));
        charactor.setFont(f4);
        return;
         
        }
          if(levelno==5)
          {
                try {
                BrightnessManager.setBrightness(100);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("T");
       bfirst.setText("P");
       bsecond.setText("S");
       bthird.setText("T");
       bfourth.setText("U");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(230,230,230));
        charactor.setFont(f5);
        return;
              
          }
    }//GEN-LAST:event_bfourthActionPerformed

    private void bsecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsecondActionPerformed
        // TODO add your handling code here:
         if(levelno==1)
        {
            try {
                BrightnessManager.setBrightness(25);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
       charactor.setText("H");
       bfirst.setText("T");
       bsecond.setText("J");
       bthird.setText("H");
       bfourth.setText("K");
       levelno=2;
       charactor.setForeground(new java.awt.Color(100,100,100));
        charactor.setFont(f1);
         
       return;
        }
         if(levelno==2)
        {
              try {
                BrightnessManager.setBrightness(50);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
           charactor.setText("L");
       bfirst.setText("M");
       bsecond.setText("J");
       bthird.setText("K");
       bfourth.setText("L");  
       levelno=3;
           charactor.setForeground(new java.awt.Color(150,150,150));
           charactor.setFont(f2);
           return;
         
        }
          if(levelno==3)
        {
             try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
          charactor.setText("A");
       bfirst.setText("Z");
       bsecond.setText("X");
       bthird.setText("B");
       bfourth.setText("A");  
       levelno++; 
        charactor.setForeground(new java.awt.Color(200,200,200));
        charactor.setFont(f3);
        return;
        
        }
          if(levelno==4)
        {
             try {
                BrightnessManager.setBrightness(75);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("Q");
       bfirst.setText("R");
       bsecond.setText("Q");
       bthird.setText("C");
       bfourth.setText("D");  
       levelno++;   
        charactor.setForeground(new java.awt.Color(220,220,220));
        charactor.setFont(f4);
        return;
        
        }
           if(levelno==5)
          {
                try {
                BrightnessManager.setBrightness(100);
            } catch (IOException ex) {
                Logger.getLogger(contrast.class.getName()).log(Level.SEVERE, null, ex);
            }
        charactor.setText("T");
       bfirst.setText("P");
       bsecond.setText("S");
       bthird.setText("T");
       bfourth.setText("U");  
       levelno++;  
       cscore++;
        charactor.setForeground(new java.awt.Color(230,230,230));
        charactor.setFont(f5);
        return;
              
          }
    }//GEN-LAST:event_bsecondActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfirst;
    private javax.swing.JButton bfourth;
    private javax.swing.JButton bsecond;
    private javax.swing.JButton bthird;
    private javax.swing.JLabel charactor;
    private javax.swing.JPanel contrastover;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel questian;
    // End of variables declaration//GEN-END:variables
 class wait implements Runnable {
    
        public void run() {
         
         while(true)
         {
       try
       {
          int i=0;
          for(i=0;i<3;i++)
          {
              Thread.sleep(1000);
          }
         
       
          
           }
        catch(Exception e)
        {
            
        }}}}





}
