/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eye;
import java.awt.Font;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import sun.security.rsa.RSACore;

/**
 *
 * @author nikhil
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public String mp3path;
    public login() {
        initComponents();
        regp.setVisible(false);
        timeUpdater updater = new timeUpdater();
       Thread t = new Thread(updater);
        t.start();
        eyeanim anim=new eyeanim();
        Thread t1 = new Thread(anim);
        
        
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regp = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        regbut = new javax.swing.JButton();
        alreadyreg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sexcombo = new javax.swing.JComboBox();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        monthcombo = new javax.swing.JComboBox();
        datecombo = new javax.swing.JComboBox();
        yearcombo = new javax.swing.JComboBox();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passmatch = new javax.swing.JLabel();
        emptyfields = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailexists = new javax.swing.JLabel();
        a1234 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginp = new javax.swing.JPanel();
        usernamelogin = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        passwordlogin = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        a123 = new javax.swing.JLabel();

        jLabel1.setText("zcxvxcbxcvb");

        regp.setBackground(new java.awt.Color(0, 0, 0));
        regp.setPreferredSize(new java.awt.Dimension(1366, 768));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        regbut.setText("reg");
        regbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbutActionPerformed(evt);
            }
        });

        alreadyreg.setText("already registered? login");
        alreadyreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alreadyregActionPerformed(evt);
            }
        });

        jLabel2.setText("First name");

        jLabel3.setText("Last name");

        jLabel4.setText("date of birth");

        jLabel5.setText("sex");

        sexcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel6.setText("email");

        monthcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jan", "feb", "mar", "april", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec", " " }));

        datecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        yearcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", " " }));
        yearcombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPasswordField2.setText("jPasswordField2");

        jPasswordField3.setText("jPasswordField2");

        jLabel9.setText("password");

        jLabel10.setText("repeat password");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel11.setText("username");

        passmatch.setForeground(new java.awt.Color(255, 0, 0));

        emptyfields.setForeground(new java.awt.Color(255, 0, 0));

        emailexists.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout regpLayout = new javax.swing.GroupLayout(regp);
        regp.setLayout(regpLayout);
        regpLayout.setHorizontalGroup(
            regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regpLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(a1234, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(passmatch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(regpLayout.createSequentialGroup()
                        .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regpLayout.createSequentialGroup()
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(regpLayout.createSequentialGroup()
                                        .addGap(518, 518, 518)
                                        .addComponent(emptyfields, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(regpLayout.createSequentialGroup()
                                        .addGap(242, 242, 242)
                                        .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sexcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(regpLayout.createSequentialGroup()
                                                .addComponent(datecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(monthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(215, 215, 215)
                                .addComponent(emailexists, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regpLayout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(regbut))
                            .addGroup(regpLayout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(alreadyreg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        regpLayout.setVerticalGroup(
            regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regpLayout.createSequentialGroup()
                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a1234, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(regpLayout.createSequentialGroup()
                        .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(regpLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(emailexists, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(regpLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(datecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(monthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(sexcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(regpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(38, 38, 38)
                                .addComponent(regbut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(alreadyreg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emptyfields, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(passmatch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(327, 327, 327))
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        loginp.setOpaque(false);
        loginp.setPreferredSize(new java.awt.Dimension(1366, 768));

        usernamelogin.setForeground(new java.awt.Color(0, 0, 255));

        login.setForeground(new java.awt.Color(0, 0, 255));
        login.setText("log in");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("new user?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        passwordlogin.setForeground(new java.awt.Color(0, 0, 255));
        passwordlogin.setText("jPasswordField1");

        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("admin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("user name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("password");

        timeLabel.setBackground(new java.awt.Color(255, 255, 255));
        timeLabel.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout loginpLayout = new javax.swing.GroupLayout(loginp);
        loginp.setLayout(loginpLayout);
        loginpLayout.setHorizontalGroup(
            loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(a123, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginpLayout.createSequentialGroup()
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(loginpLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(49, 49, 49)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginpLayout.createSequentialGroup()
                                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernamelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addGap(209, 209, 209))
                    .addGroup(loginpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(281, Short.MAX_VALUE))))
        );
        loginpLayout.setVerticalGroup(
            loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpLayout.createSequentialGroup()
                .addComponent(a123, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 481, Short.MAX_VALUE))
            .addGroup(loginpLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usernamelogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passwordlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(login)
                .addGap(18, 18, 18)
                .addGroup(loginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginp, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel1.remove(loginp);
        jPanel1.add(regp);
        regp.setSize(this.getWidth(),this.getHeight());
        regp.setVisible(true);
        jPanel1.repaint();
        jPanel1.revalidate();
        eyeanimreg anim=new eyeanimreg();
        Thread t2 = new Thread(anim);
        
        
        t2.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alreadyregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alreadyregActionPerformed
        // TODO add your handling code here:
        jPanel1.remove(regp);
        jPanel1.add(loginp);
        jPanel1.repaint();
        jPanel1.revalidate();
        
    }//GEN-LAST:event_alreadyregActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void regbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbutActionPerformed
        // TODO add your handling code here:
        
        Connection conn=null;
        Statement stat=null;
        try{
           // Class.forName(org.apache.derbyclient.jdbc.ClientDriver);
        //conn=DriverManager.getConnection("jdbc:derby://localhost:1527/eyetest","nikhil","000");
            
            conn=DriverManager.getConnection("jdbc:derby://localhost:1527/userdata","nikhil","biju");
        stat=conn.createStatement();
        System.out.println("succes");
       String year= yearcombo.getSelectedItem().toString();
       int yearn=2016-Integer.parseInt(year);
       String fname=firstname.getText();
       String lname=lastname.getText();
       String sx=sexcombo.getSelectedItem().toString();
       String emailr=email.getText();
     //  int phoneno=Integer.parseInt(phone.getText());
       String usernme=username.getText();
        String passwordr=new String(jPasswordField3.getPassword());
       String passwordf=new String(jPasswordField2.getPassword());
     /*  if(fname.equals("")||lname.equals("")||emailr.equals("")||Integer.toString(phoneno).equals("")||usernme.equals("")||passwordr.equals(""))
       {
           emptyfields.setText("somefields are empty");
       }*/
       //else
      // {
       
       if(passwordr.equals(passwordf))
       
       { passmatch.setText("");
           String check="select * from userdata";
            ResultSet rs=stat.executeQuery(check);
            while(rs.next())
            {
                String checkuser=rs.getString("username");
                
                if(checkuser.equals(usernme))
                {
                    emptyfields.setText("username exists");
                    return;
                }
                
                       
                
            }
            while(rs.next())
            {
                String checkemail=rs.getString("email");
                if(checkemail.equals(emailr))
                {
                    emailexists.setText("emailid exists");
                }
                return;
            }
           
            emptyfields.setText("");
            emailexists.setText("");
        String sqlinsert="insert into userdata(firstname,lastname,age,sex,email,username,password)"
                + " values('"+fname+"','"+lname+"',"+yearn+",'"+sx+"','"+emailr+"','"
                +usernme+"','"+passwordr+"')";
        
           JOptionPane.showMessageDialog(null,"registration succesful please login");
        
        System.out.println( );
        stat.executeUpdate(sqlinsert); 
     
        }
        
        else
        {
          passmatch.setText("passwords not matching");
                }
       
       conn.close();
       stat.close();
        }
        
       catch(SQLException e)
       {  // emptyfields.setText(e.getMessage());
           System.err.println(e.getMessage());
           System.out.println(e.getErrorCode());
       }
        
     finally{
//finally block used to close resources
try{
if(stat!=null)    
stat.close();
}catch(SQLException se2){
}// nothing we can do
try{
if(conn!=null)
conn.close();
}catch(SQLException se){
se.printStackTrace();
}

        }    
    }//GEN-LAST:event_regbutActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
       
        
       // String sqliinsert="insert into userdata (firstname,lastname,age,sex,email,phone)values("
              //  +firstname.getText()+","+lastname.getText()+","+);
    }//GEN-LAST:event_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String usrnme=usernamelogin.getText();
        String usrpassword=new String(passwordlogin.getPassword());
        Connection conne=null;
        Statement state=null;
        try{
           // Class.forName(org.apache.derbyclient.jdbc.ClientDriver);
        //conn=DriverManager.getConnection("jdbc:derby://localhost:1527/eyetest","nikhil","000");
            
            conne=DriverManager.getConnection("jdbc:derby://localhost:1527/userdata","nikhil","biju");
        state=conne.createStatement();
        String check="select username,password from userdata";
         
        ResultSet rse=state.executeQuery(check);
 
      // String pass =rs.getString("password");
        
     // System.out.println(rs.getString("password"));

//System.out.println(usr+psw+"\n"+usrnme+usrpassword);
            
 int temp=0;
//if(usr.equals(usrnme)&&psw.equals(usrpassword))
   while(rse.next())
       {
        
           String uname=rse.getString("USERNAME");
           String password=rse.getString("PASSWORD");
           System.out.println(uname+password);
           if((usrnme.equals(uname))&&(usrpassword.equals(password)))
           {  
   
  System.out.println("lgined");
  Functionselect fc= new Functionselect();
 
  jPanel1.remove(loginp);
   jPanel1.add(fc);
   jPanel1.setVisible(true);
  fc.setVisible(true);
  fc.setSize(this.getWidth(),this.getHeight());
  jPanel1.repaint();
  jPanel1.revalidate();
  temp++;
  mp3path="C:\\\\Users\\\\nikhil\\\\Documents\\\\NetBeansProjects\\\\eye\\\\eyecare.mp3";
//  MP3 m=new MP3("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyecare.mp3");
 // m.play();
  music play = new music();
       Thread t = new Thread(play);
        t.start();
  return;
    }
       }   

if(temp==0)
{
    
    JOptionPane.showMessageDialog(null,"invalid user name or password");
    
    
}
    //    }
        
       }   
       
          

        
        catch(SQLException e)
       {  // emptyfields.setText(e.getMessage());
           System.err.println(e.getMessage());
           System.out.println(e.getErrorCode());
       }
        
        
    }//GEN-LAST:event_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a123;
    private javax.swing.JLabel a1234;
    private javax.swing.JButton alreadyreg;
    private javax.swing.JComboBox datecombo;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailexists;
    private javax.swing.JLabel emptyfields;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginp;
    private javax.swing.JComboBox monthcombo;
    private javax.swing.JLabel passmatch;
    private javax.swing.JPasswordField passwordlogin;
    private javax.swing.JButton regbut;
    private javax.swing.JPanel regp;
    private javax.swing.JComboBox sexcombo;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usernamelogin;
    private javax.swing.JComboBox yearcombo;
    // End of variables declaration//GEN-END:variables
class timeUpdater implements Runnable {
        @Override
        public void run() { Font f=new Font("Microsoft Himalaya",12,200);Font f4=new Font("Microsoft Himalaya",12,200);Font f3=new Font("Microsoft Himalaya",12,120);Font f2=new Font("Microsoft Himalaya",12,150);Font f1=new Font("Microsoft Himalaya",12,100);timeLabel.setFont(f1);
            
        
        
        
        while (true) {
                //Calendar cl = Calendar.getInstance();
              //  String time = cl.get(Calendar.HOUR) + ":" + cl.get(Calendar.MINUTE) + ":" + cl.get(Calendar.SECOND) + ":" + cl.get(Calendar.MILLISECOND);
                
                try {timeLabel.setFont(f1);timeLabel.setText("e");
                    Thread.sleep(100);
                    
                    timeLabel.setText("ey");
                    Thread.sleep(100);
                    timeLabel.setText("eye");
                    Thread.sleep(100);
                    timeLabel.setText("eye ");
                    Thread.sleep(100);
                    timeLabel.setText("eye t");
                    Thread.sleep(100);
                    timeLabel.setText("eye te");
                    Thread.sleep(100);
                    timeLabel.setText("eye tes");
                    Thread.sleep(100);
                    timeLabel.setText("eye test");
                    Thread.sleep(1000);
                    timeLabel.setFont(f3);
                    Thread.sleep(50);
                     timeLabel.setFont(f2);
                    Thread.sleep(50);
                    timeLabel.setFont(f4);
                    Thread.sleep(50);
                    timeLabel.setFont(f);
                    Thread.sleep(1000);
                    timeLabel.setText("");
                    Thread.sleep(100);
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                } 
                catch (InterruptedException ex) {
                    System.err.println("Cant Sleep");
                }
            }
        }
   
    
   }
class eyeanim implements Runnable {
    @Override
        public void run() {
       while(true)
       {
           try{
           a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefirstb.jpg"));
          
           Thread.sleep(1);
           a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyesecondb.jpg"));
           
           Thread.sleep(1);
          a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyethirdb.jpg"));
           Thread.sleep(1);
            a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefourthb.jpg"));
           Thread.sleep(1);
           
          a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefifthb.jpg"));
          Thread.sleep(1);
           
          a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyesixthb.jpg"));
         Thread.sleep(1);
         a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyeseventhb.jpg"));
         Thread.sleep(1);
        
         
         //  a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyebal35.jpg"));
          //Thread.sleep(250);
           }
           catch(InterruptedException e)
           {
               
           }
       }
        
        }
        
}
class eyeanimreg implements Runnable {
    @Override
        public void run() {
       while(true)
       {
           try{
           a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefirstb.jpg"));
          
           Thread.sleep(1);
           a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyesecondb.jpg"));
           
           Thread.sleep(1);
          a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyethirdb.jpg"));
           Thread.sleep(1);
            a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefourthb.jpg"));
           Thread.sleep(1);
           
          a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyefifthb.jpg"));
          Thread.sleep(1);
           
          a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyesixthb.jpg"));
         Thread.sleep(1);
         a1234.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyeseventhb.jpg"));
         Thread.sleep(1);
        
         
         //  a123.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhil\\Documents\\NetBeansProjects\\eye\\eyebal35.jpg"));
          //Thread.sleep(250);
           }
           catch(InterruptedException e)
           {
               
           }
       }}}
   class music implements Runnable {
    
        public void run() {
           
       try
       {
           
         MP3 m=new MP3(mp3path);
         m.play();
           
           
           
           
           }
        catch(Exception e)
        {
            
        }}}
       
       
        
        
        

}


